# Can reference current directory
#CONFIG_DIR=/Users/$USER/repos/tooling/configs/zsh_config
CONFIG_DIR=~/repos/tooling/configs/zsh_config
source $CONFIG_DIR/master.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
